# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import gpss_pb2 as gpss__pb2


class GpssStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Connect = channel.unary_unary(
        '/api.Gpss/Connect',
        request_serializer=gpss__pb2.ConnectRequest.SerializeToString,
        response_deserializer=gpss__pb2.Session.FromString,
        )
    self.Disconnect = channel.unary_unary(
        '/api.Gpss/Disconnect',
        request_serializer=gpss__pb2.Session.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.Open = channel.unary_unary(
        '/api.Gpss/Open',
        request_serializer=gpss__pb2.OpenRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.Write = channel.unary_unary(
        '/api.Gpss/Write',
        request_serializer=gpss__pb2.WriteRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.Close = channel.unary_unary(
        '/api.Gpss/Close',
        request_serializer=gpss__pb2.CloseRequest.SerializeToString,
        response_deserializer=gpss__pb2.TransferStats.FromString,
        )
    self.ListSchema = channel.unary_unary(
        '/api.Gpss/ListSchema',
        request_serializer=gpss__pb2.ListSchemaRequest.SerializeToString,
        response_deserializer=gpss__pb2.Schemas.FromString,
        )
    self.ListTable = channel.unary_unary(
        '/api.Gpss/ListTable',
        request_serializer=gpss__pb2.ListTableRequest.SerializeToString,
        response_deserializer=gpss__pb2.Tables.FromString,
        )
    self.DescribeTable = channel.unary_unary(
        '/api.Gpss/DescribeTable',
        request_serializer=gpss__pb2.DescribeTableRequest.SerializeToString,
        response_deserializer=gpss__pb2.Columns.FromString,
        )


class GpssServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Connect(self, request, context):
    """Establish a connection to Greenplum Database; returns a Session object
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Disconnect(self, request, context):
    """Disconnect, freeing all resources allocated for a session
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Open(self, request, context):
    """Prepare and open a table for write
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Write(self, request, context):
    """Write data to table
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Close(self, request, context):
    """Close a write operation
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListSchema(self, request, context):
    """List all available schemas in a database
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListTable(self, request, context):
    """List all tables and views in a schema
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DescribeTable(self, request, context):
    """Decribe table metadata(column name and column type)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GpssServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Connect': grpc.unary_unary_rpc_method_handler(
          servicer.Connect,
          request_deserializer=gpss__pb2.ConnectRequest.FromString,
          response_serializer=gpss__pb2.Session.SerializeToString,
      ),
      'Disconnect': grpc.unary_unary_rpc_method_handler(
          servicer.Disconnect,
          request_deserializer=gpss__pb2.Session.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'Open': grpc.unary_unary_rpc_method_handler(
          servicer.Open,
          request_deserializer=gpss__pb2.OpenRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'Write': grpc.unary_unary_rpc_method_handler(
          servicer.Write,
          request_deserializer=gpss__pb2.WriteRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'Close': grpc.unary_unary_rpc_method_handler(
          servicer.Close,
          request_deserializer=gpss__pb2.CloseRequest.FromString,
          response_serializer=gpss__pb2.TransferStats.SerializeToString,
      ),
      'ListSchema': grpc.unary_unary_rpc_method_handler(
          servicer.ListSchema,
          request_deserializer=gpss__pb2.ListSchemaRequest.FromString,
          response_serializer=gpss__pb2.Schemas.SerializeToString,
      ),
      'ListTable': grpc.unary_unary_rpc_method_handler(
          servicer.ListTable,
          request_deserializer=gpss__pb2.ListTableRequest.FromString,
          response_serializer=gpss__pb2.Tables.SerializeToString,
      ),
      'DescribeTable': grpc.unary_unary_rpc_method_handler(
          servicer.DescribeTable,
          request_deserializer=gpss__pb2.DescribeTableRequest.FromString,
          response_serializer=gpss__pb2.Columns.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'api.Gpss', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
